export { BetterCodeSoulPlugin } from './plugin.js'
export { db } from './services/Database.js'
export { tokenTracker } from './services/TokenTracker.js'
export { costCalculator } from './services/CostCalculator.js'
export { modelRegistry } from './services/ModelRegistry.js'
export { authReader } from './services/AuthReader.js'
export { configPatcher } from './services/ConfigPatcher.js'
export { graphifyService } from './services/GraphifyService.js'
export { contextModeService } from './services/ContextModeService.js'
export { doctorService } from './services/DoctorService.js'
export { Orchestrator } from './subagents/Orchestrator.js'
export { startDashboardServer } from './web/DashboardServer.js'
export { formatTokens, formatCost, formatDuration, formatRelativeTime, formatBytes } from './utils/format.js'
export { paths } from './utils/platform.js'
export { logger } from './utils/logger.js'

import { BetterCodeSoulPlugin } from './plugin.js'
export default BetterCodeSoulPlugin
